#!/usr/bin/env bash
# research_q3 release-mechanism comparison launcher (runs on the cloud VM at
# ~/efficient-storage-in-edge-scenarios).
# usage: bash research_q3_launch_run.sh <env_file> <label> <seed>
#   e.g. bash research_q3_launch_run.sh arm_stabilized.env rq3rel_cal_s1 42
# research_q3 arms: RELEASE_MECHANISM in {off, drained, immediate, stabilized}
# (docs/operation/testing/experiment/research_q3). Resource shaping matches the
# RQ3 v3 storage-constrained regime (EDGE_CPUS=0.08 / STORAGE_CPUS=0.25) so the
# release mechanism is the only variable axis between runs.
# Uses the canonical phases.json (no PHASES_CONFIG override).
#
# 2026-09-02 fix: the controller env is base (osken-controller.env) + ONE
# override file, but the campaign needs BOTH the canonical override
# (current_state_integrated.env: MAX_DYNAMIC_COMPUTE=3, SS_ENABLED=1,
# recalibrated scale-up/down thresholds) and the arm env (release-mechanism
# knobs). build_network_setup.sh / run_experiment.sh each accept a single
# OSKEN_ENV_OVERRIDE_FILE, so we merge canonical + arm into one temp override
# (arm wins on duplicate keys, one line per key so the exact-line validation
# in build_network_setup.sh passes) and pass the merged file.
set -u
cd ~/efficient-storage-in-edge-scenarios || exit 1
ENV_FILE="$1"
LABEL="$2"
SEED="${3:-42}"

CANONICAL_ENV="source/scripts/testing/controller_env_overrides/current_state_integrated.env"
ARM_ENV="docs/operation/testing/experiment/research_q3/env/$ENV_FILE"
MERGED_ENV="$(mktemp /tmp/rq3rel_merged_XXXXXX.env)"
python3 - "$CANONICAL_ENV" "$ARM_ENV" "$MERGED_ENV" <<'PYEOF'
import sys
canonical_path, arm_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
keys = []
values = {}
for path in (canonical_path, arm_path):
    with open(path) as f:
        for line in f:
            line = line.rstrip("\r\n")
            s = line.strip()
            if not s or s.startswith("#") or "=" not in s:
                continue
            key = s.split("=", 1)[0].strip()
            if key not in values:
                keys.append(key)
            values[key] = s
with open(out_path, "w") as f:
    f.write("# research_q3 merged controller override (generated by research_q3_launch_run.sh)\n")
    f.write(f"#   canonical: {canonical_path}\n")
    f.write(f"#   arm      : {arm_path}\n")
    f.write("#   arm entries override canonical entries with the same key.\n")
    for key in keys:
        f.write(values[key] + "\n")
PYEOF

ulimit -n 65535
exec sudo -n make -C source/scripts setup_network create_clients setup_test_data run_experiment \
  OSKEN_ENV_OVERRIDE_FILE="$MERGED_ENV" \
  RUN_LABEL="$LABEL" \
  CLIENTS=24 CONTENT_ITEMS=3000 USERS=100 DATA_SEED=42 \
  TRAFFIC_DRIVER_MODE=open_loop CURL_MAX_TIME=300 INFLIGHT_WINDOW=1024 DRAIN_S=30 \
  STORAGE_CPUS=0.25 EDGE_CPUS=0.08 WAN_RTT_MS=185 RANDOM_SEED="${SEED:-42}" \
  EDGE_MONGO_READ_PREFERENCE=secondaryPreferred EDGE_MONGO_MAX_POOL_SIZE=6 \
  VIP_DATA_PER_CONNECTION_FLOWS=1 EDGE_FLOW_ISOLATION=1 \
  OVERLOAD_MIN_REQUESTS=60 \
  SKIP_CLIENTS=1 SKIP_SEED=1 SKIP_SNAPSHOT=1
